apiVersion: lambdo.io/v1alpha1
kind: Config
api:
  network:
    # The host on which the API server will listen
    webHost: 0.0.0.0
    # The port on which the API server will listen
    webPort: 3000
    # Bridge name
    bridge: lambdo0
    # The IP address of the bridge
    ip: 10.0.50.0/8

  imageManager:
    # Folder path for the images
    imagesFolder: /var/lib/lambdo/images

